### ISSUE TITLE
consider renaming the module to python_usernames

### ISSUE THREAD

**Issue by woutervh** [theskumar/python-usernames#6]
The name of a python-package is used to install it:

`> pip install <package-name>`

The package-name must be unique in pypi,
the associated unique module-name  is the lowercased package-name with dashes replaced by underscores.

`> pip install foo-bar`
`>>> import foo_bar`

so a package named "python-usernames", should use a module named "python_usernames".

Imagine there is another package named "usernames", 
then pip installing your package will remove the code of that package
without complaining.

This is a proper example:
https://github.com/yoavravid/RedditUsernames

**Comment by woutervh** [comment]
Same issue:
> pip install dotenv                 # correct module-name: dotenv
> pip install django-dotenv    # wrong module-name: dotenv
> pip install python-dotenv    # wrong module-name: dotenv

**Comment by theskumar** [comment]
@woutervh I'm onboard with your proposal. I'll have the package names changed. Thanks for creating this issue.

**Comment by woutervh** [comment]
Sorry for the gazillion typos in my message.
